import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { PrivateLayout } from '../src/layouts';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

Home.getLayout = PrivateLayout;
export default Home;
